/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pap2025;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCanBeInstantiated() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should be instantiable");
    }
}
