/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pap2025;

import pap2025.logica.ControladorFachada;
import pap2025.interfaz.IControladorFachada;
import pap2025.presentacion.VentanaPrincipal;
import pap2025.logica.Lector;
import pap2025.logica.Bibliotecario;
import pap2025.logica.Libro;
import pap2025.logica.ArtEspeciales;
import pap2025.logica.EstadoL;
import pap2025.logica.EstadoP;
import pap2025.logica.Material;
import pap2025.datatypes.DTFecha;
import pap2025.datatypes.DTDimensiones;
import pap2025.persistencia.ConfiguracionBD;
import javax.swing.SwingUtilities;
import java.util.List;

public class App {
    
    public static void main(String[] args) {
        System.out.println("🚀 Iniciando Sistema de Biblioteca...");
        
        // Inicializar conexión a la base de datos
        if (!ConfiguracionBD.inicializarConexion()) {
            System.err.println("❌ No se pudo conectar a la base de datos. Verifica la configuración.");
            System.exit(1);
        }
        
        // Crear instancia del controlador fachada
        IControladorFachada controlador = ControladorFachada.getInstancia();
        
        // Lanzar la ventana principal en el EDT (Event Dispatch Thread)
        SwingUtilities.invokeLater(() -> {
            try {
                new VentanaPrincipal();
                System.out.println("✅ Ventana Principal abierta correctamente");
            } catch (Exception e) {
                System.err.println("❌ Error al abrir la ventana principal: " + e.getMessage());
                e.printStackTrace();
            }
        });
        
        // Agregar shutdown hook para cerrar la conexión
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            ConfiguracionBD.cerrarConexion();
        }));
    }
    
}
